--<ScriptOptions statementTerminator=";"/>

CREATE TABLE KM_EVENT (
		ID_EVENT NUMBER(38 , 0) NOT NULL,
		ID_EVENT_CALENDAR NUMBER(38 , 0) NOT NULL,
		ID_EVENT_RESULT NUMBER(38 , 0),
		ID_EVENT_STATUS NUMBER(38 , 0),
		ID_EXECUTOR NUMBER(38 , 0),
		START_DATE DATE,
		EXECUTED_DATE DATE,
		PLAN_DATE DATE NOT NULL,
		RESULT_NOTES VARCHAR2(4000),
		SANCTION_TEXT VARCHAR2(1024),
		SANCTION_DATE DATE,
		SANCTION_VALUE NUMBER(22 , 0),
		SANCTION_UNIT VARCHAR2(10)
	);

CREATE UNIQUE INDEX KM_EVENT_PK ON KM_EVENT (ID_EVENT ASC);

ALTER TABLE KM_EVENT ADD CONSTRAINT KM_EVENT_PK PRIMARY KEY (ID_EVENT);

ALTER TABLE KM_EVENT ADD CONSTRAINT KM_EVENT_FK02 FOREIGN KEY (ID_EVENT_RESULT)
	REFERENCES CD_EVENT_RESULT (ID_EVENT_RESULT)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE KM_EVENT ADD CONSTRAINT KM_EVENT_FK03 FOREIGN KEY (ID_EVENT_STATUS)
	REFERENCES KM_EVENT_STATUS (ID_EVENT_STATUS)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE KM_EVENT ADD CONSTRAINT KM_EVENT_FK01 FOREIGN KEY (ID_EVENT_CALENDAR)
	REFERENCES KM_EVENT_CALENDAR (ID_EVENT_CALENDAR)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

