--<ScriptOptions statementTerminator=";"/>

CREATE TABLE CD_FKR_TYPE (
		ID_FKR_TYPE NUMBER(38 , 0) NOT NULL,
		FKR_TYPE VARCHAR2(2048) NOT NULL,
		ID_FKR_GROUP NUMBER(38 , 0),
		FKR_CODE VARCHAR2(32),
		FKR_KIND NUMBER(38 , 0),
		IS_SIGNIFICANT NUMBER(38 , 0) NOT NULL,
		IS_ACTIVE NUMBER(38 , 0) DEFAULT 1  NOT NULL
	);

CREATE UNIQUE INDEX CD_FKR_TYPE_PK ON CD_FKR_TYPE (ID_FKR_TYPE ASC);

ALTER TABLE CD_FKR_TYPE ADD CONSTRAINT CD_FKR_TYPE_PK PRIMARY KEY (ID_FKR_TYPE);

ALTER TABLE CD_FKR_TYPE ADD CONSTRAINT CD_FKR_TYPE_FK01 FOREIGN KEY (ID_FKR_GROUP)
	REFERENCES CD_FKR_GROUP (ID_FKR_GROUP)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

