--<ScriptOptions statementTerminator=";"/>

CREATE TABLE APPFILES (
		UNID VARCHAR2(128) NOT NULL,
		FILENAME VARCHAR2(256),
		FILEDATA BLOB,
		FILETYPE VARCHAR2(256),
		ID_OWNER VARCHAR2(64),
		OWNER_TYPE NUMBER(22 , 0),
		WHO_ADD NUMBER(22 , 0),
		DATE_OF_ADDITION DATE,
		DATE_OF_EXPIRATION DATE,
		ISACCEPTED NUMBER(22 , 0),
		WHOACCEPTED NUMBER(22 , 0),
		DATE_OF_ACCEPT DATE,
		SIGNATURE BLOB,
		ID_APPL NUMBER(22 , 0),
		ID_GROUP NUMBER(22 , 0),
		FORCC CHAR(1) DEFAULT 'y',
		CONTENTTYPE VARCHAR2(256) DEFAULT 'application/octet-stream'  NOT NULL,
		ID_DOCUMENT_TYPE NUMBER(38 , 0) DEFAULT null,
		FILEURL VARCHAR2(512),
		WHO_DEL NUMBER(22 , 0),
		DATE_OF_DEL DATE,
		ACCEPT_SIGNATURE BLOB
	);
	
	select UNID from APPFILES where rownum < 10
	select UNID, FILEDATA from APPFILES where rownum < 3

CREATE INDEX APPFILES_FK4_I ON APPFILES (ID_GROUP ASC);

CREATE INDEX APPFILES_FK1_I ON APPFILES (WHO_ADD ASC);

CREATE INDEX APPFILES_FK2_I ON APPFILES (WHOACCEPTED ASC);

CREATE INDEX APPFILES_FK03_I ON APPFILES (ID_DOCUMENT_TYPE ASC);

CREATE UNIQUE INDEX PK_APPFILES ON APPFILES (UNID ASC);

ALTER TABLE APPFILES ADD CONSTRAINT PK_APPFILES PRIMARY KEY (UNID);

ALTER TABLE APPFILES ADD CONSTRAINT APPFILES_FK03 FOREIGN KEY (ID_DOCUMENT_TYPE)
	REFERENCES DOCUMENTS_TYPE (ID_DOCUMENT_TYPE)
	ON DELETE SET NULL
	ON UPDATE CASCADE;

ALTER TABLE APPFILES ADD CONSTRAINT APPFILES_FK2 FOREIGN KEY (WHOACCEPTED)
	REFERENCES USERS (ID_USER)
	ON DELETE SET NULL
	ON UPDATE CASCADE;

ALTER TABLE APPFILES ADD CONSTRAINT APPFILES_FK4 FOREIGN KEY (ID_GROUP)
	REFERENCES DOCUMENT_GROUP (ID_GROUP)
	ON DELETE SET NULL
	ON UPDATE CASCADE;

ALTER TABLE APPFILES ADD CONSTRAINT APPFILES_FK1 FOREIGN KEY (WHO_ADD)
	REFERENCES USERS (ID_USER)
	ON DELETE SET NULL
	ON UPDATE CASCADE;

