--<ScriptOptions statementTerminator=";"/>

CREATE TABLE CPS_MEMBERSHIP (
		ID_MEMBERSHIP NUMBER(38 , 0) NOT NULL,
		USER_ID_ NVARCHAR2(64) NOT NULL,
		GROUP_ID_ NVARCHAR2(64) NOT NULL,
		IS_ACTIVE NUMBER(1 , 0) DEFAULT 1  NOT NULL
	);

CREATE UNIQUE INDEX CPS_MEMBERSHIP_ID_UK ON CPS_MEMBERSHIP (ID_MEMBERSHIP ASC);

CREATE UNIQUE INDEX CPS_MEMBERSHIP_USER_GROUP_PK ON CPS_MEMBERSHIP (USER_ID_ ASC, GROUP_ID_ ASC);

CREATE UNIQUE INDEX CPS_MEMBERSHIP_USER_GROUP_UQ ON CPS_MEMBERSHIP (GROUP_ID_ ASC);

ALTER TABLE CPS_MEMBERSHIP ADD CONSTRAINT CPS_MEMBERSHIP_USER_GROUP_PK PRIMARY KEY (USER_ID_, GROUP_ID_);

select * from CPS_MEMBERSHIP where rownum < 10

select cps_m.GROUP_ID_ cps_r_id, cps_r.NAME_ cps_r_name 
	from CPS_MEMBERSHIP cps_m
	left outer join CPS_ROLE cps_r on cps_m.GROUP_ID_ = cps_r.ID_
	where USER_ID_ = 'adminwf'
