--<ScriptOptions statementTerminator=";"/>

CREATE TABLE CPS_ROLE (
		ID_ROLE NUMBER(38 , 0) NOT NULL,
		ID_ NVARCHAR2(64) NOT NULL,
		REV_ NUMBER(22 , 0),
		NAME_ NVARCHAR2(255) NOT NULL,
		TYPE_ NVARCHAR2(255),
		PARENT_ROLE_KEY NVARCHAR2(64)
	);

CREATE UNIQUE INDEX CPS_ROLE_ID_UK ON CPS_ROLE (ID_ROLE ASC);

CREATE UNIQUE INDEX CPS_ROLE_PK ON CPS_ROLE (ID_ ASC);

ALTER TABLE CPS_ROLE ADD CONSTRAINT CPS_ROLE_PK PRIMARY KEY (ID_);

ALTER TABLE CPS_ROLE ADD CONSTRAINT CPS_ROLE_PARENT_FK FOREIGN KEY (PARENT_ROLE_KEY)
	REFERENCES CPS_ROLE (ID_)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;
	
select count(*) from CPS_ROLE	
select * from CPS_ROLE

select count(*) from v_cps_role_hierarchy
select * from v_cps_role_hierarchy

select * from users where rownum < 10

