--<ScriptOptions statementTerminator=";"/>

CREATE TABLE KM_EVENT_TYPE (
		ID_EVENT_TYPE NUMBER(38 , 0) NOT NULL,
		EVENT_TYPE_NAME VARCHAR2(1024) NOT NULL,
		ID_CONFIRMATION_TYPE NUMBER(38 , 0),
		ID_DOCUMENTS_TYPE NUMBER(38 , 0),
		ID_PUNITIVE_MEASURE NUMBER(38 , 0),
		ID_REPEAT_TYPE NUMBER(38 , 0),
		REPEAT_PERIOD NUMBER(38 , 0),
		REPEAT_PERIOD_KIND NUMBER(38 , 0),
		DUE_DATE_PERIOD NUMBER(38 , 0),
		DUE_DATE_PERIOD_KIND NUMBER(38 , 0),
		NOTIFY_PERIOD NUMBER(38 , 0),
		NOTIFY_PERIOD_KIND NUMBER(38 , 0),
		EVENT_CAUSE VARCHAR2(1024),
		CAUSE_DOC_NUMBER VARCHAR2(50),
		CAUSE_DOC_DATE DATE,
		IS_SANCTION_POSSIBLE NUMBER(38 , 0),
		ID_EVENT_GROUP NUMBER(38 , 0) NOT NULL,
		CP_STAGE VARCHAR2(1024),
		CRF_PROCESS VARCHAR2(1024),
		DRF_PROCESS VARCHAR2(1024),
		ID_QUERY_CREATION NUMBER(38 , 0),
		ID_KM_CREATION NUMBER(38 , 0),
		ID_KM_EXECUTION NUMBER(38 , 0),
		ID_KM_APPROVAL NUMBER(38 , 0),
		IS_ACTIVE VARCHAR2(1),
		REPEAT_PERIOD_WEEKEND NUMBER(1 , 0) DEFAULT 0  NOT NULL,
		REPEAT_PERIOD_WEEKEND_EXCLUDE NUMBER(1 , 0) DEFAULT 0  NOT NULL,
		NOTIFY_AT_DAY NUMBER(1 , 0) DEFAULT 0  NOT NULL,
		NOTIFY_AFTER NUMBER(1 , 0) DEFAULT 0  NOT NULL,
		NOTIFY_LINK_MSG NUMBER(1 , 0) DEFAULT 0  NOT NULL
	);

CREATE UNIQUE INDEX KM_EVENT_TYPE_PK ON KM_EVENT_TYPE (ID_EVENT_TYPE ASC);

ALTER TABLE KM_EVENT_TYPE ADD CONSTRAINT KM_EVENT_TYPE_PK PRIMARY KEY (ID_EVENT_TYPE);

ALTER TABLE KM_EVENT_TYPE ADD CONSTRAINT KM_EVENT_GROUP_FK FOREIGN KEY (ID_EVENT_GROUP)
	REFERENCES KM_EVENT_GROUP (ID_EVENT_GROUP)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE KM_EVENT_TYPE ADD CONSTRAINT KM_EVENT_TYPE_FK10 FOREIGN KEY (ID_REPEAT_TYPE)
	REFERENCES KM_REPEAT_TYPE (ID_REPEAT_TYPE)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE KM_EVENT_TYPE ADD CONSTRAINT KM_EVENT_TYPE_CONFIRMATION_FK FOREIGN KEY (ID_CONFIRMATION_TYPE)
	REFERENCES KM_CONFIRMATION_TYPE (ID_CONFIRMATION_TYPE)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

