--<ScriptOptions statementTerminator=";"/>

CREATE TABLE KM_EVENT_CALENDAR_DATES (
		ID_EVENT_CALENDAR NUMBER(38 , 0) NOT NULL,
		PLAN_DT DATE NOT NULL
	);

CREATE UNIQUE INDEX KM_EVENT_CAL_PK ON KM_EVENT_CALENDAR_DATES (ID_EVENT_CALENDAR ASC);

ALTER TABLE KM_EVENT_CALENDAR_DATES ADD CONSTRAINT KM_EVENT_CAL_PK PRIMARY KEY (ID_EVENT_CALENDAR);

ALTER TABLE KM_EVENT_CALENDAR_DATES ADD CONSTRAINT KM_EVENT_CAL_FK1 FOREIGN KEY (ID_EVENT_CALENDAR)
	REFERENCES KM_EVENT_CALENDAR (ID_EVENT_CALENDAR)
	ON DELETE CASCADE
	ON UPDATE CASCADE;

