--<ScriptOptions statementTerminator=";"/>

CREATE VIEW V_CPS_CREDIT_DEAL_NUMBER (ID_MDTASK, OFFICIAL_DATE, OFFICIAL_NUMBER, DOC_CONTRACTOR_NUMBER, ID_CREDIT_DOCUMENTATION, ID_COMMON_DEAL_CONCLUSION) 
WITH CASCADED CHECK OPTION;

