--<ScriptOptions statementTerminator=";"/>

CREATE TABLE USERS (
		ID_USER NUMBER(22 , 0) NOT NULL,
		MAIL_USER NVARCHAR2(128),
		IP_USER NVARCHAR2(128),
		LOGIN NVARCHAR2(2000),
		SURNAME NVARCHAR2(100),
		NAME NVARCHAR2(100),
		PATRONYMIC NVARCHAR2(100),
		ID_DEPARTMENT NUMBER(22 , 0) NOT NULL,
		IS_ACTIVE NUMBER(22 , 0) DEFAULT 1  NOT NULL,
		ID_BOSS NUMBER(38 , 0),
		ID_ASSIGNMENT NUMBER(22 , 0),
		ID_SUBSTITUTE NUMBER(38 , 0) DEFAULT null,
		ID_ASSIGNEE NUMBER(38 , 0) DEFAULT null
	);
	
    select u.id_user u_id, u.mail_user u_email, u.login u_login, u.surname u_last_name,
    	u.name u_first_name, patronymic u_patronymic,
    	dep.id_department dep_id, dep.fullname dep_name 
    	from users u
    	inner join DEPARTMENTS dep on u.id_department=dep.id_department
    		where login = 'khapaa'
    		
    select * from departments where rownum < 5		

CREATE INDEX USERS_SUBPARENT_FK_I ON USERS (ID_SUBSTITUTE ASC);

CREATE INDEX USERS_ASSIGNEEBOSS_FK_I ON USERS (ID_ASSIGNEE ASC);

CREATE INDEX USERS_SELF_FK_I ON USERS (ID_BOSS ASC);

CREATE INDEX USER_ASSIGNMENT_FK_I ON USERS (ID_ASSIGNMENT ASC);

CREATE UNIQUE INDEX USERS_PK ON USERS (ID_USER ASC);

CREATE UNIQUE INDEX USERS_LOGIN_UK_LC1 ON USERS (null);

CREATE UNIQUE INDEX USERS_UK1 ON USERS (LOGIN ASC);

ALTER TABLE USERS ADD CONSTRAINT USERS_PK PRIMARY KEY (ID_USER);

ALTER TABLE USERS ADD CONSTRAINT USER_ASSIGNMENT_FK FOREIGN KEY (ID_ASSIGNMENT)
	REFERENCES CC_ASSIGNMENT (ID_ASSIGNMENT)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE USERS ADD CONSTRAINT USERS_ASSIGNEEBOSS_FK FOREIGN KEY (ID_ASSIGNEE)
	REFERENCES USERS (ID_USER)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE USERS ADD CONSTRAINT USERS_DEPARTMENTS_FK FOREIGN KEY (ID_DEPARTMENT)
	REFERENCES DEPARTMENTS (ID_DEPARTMENT)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE USERS ADD CONSTRAINT USERS_SELF_FK FOREIGN KEY (ID_BOSS)
	REFERENCES USERS (ID_USER)
	ON DELETE CASCADE
	ON UPDATE CASCADE;

ALTER TABLE USERS ADD CONSTRAINT USERS_SUBPARENT_FK FOREIGN KEY (ID_SUBSTITUTE)
	REFERENCES USERS (ID_USER)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

